### ISSUE TITLE
Open in New tab/window creates two new tabs/windows

### ISSUE THREAD

**Issue by danieltaylor** [hbang/TermHere#13] opened 2017-02-28 06:08 UTC
If there is not already a tab or window open, having the new tab/window option selected causes two tabs or windows to be opened.

**Comment by nuno-azevedo** [comment] 2017-03-09 12:32
I can confirm this, it's a little bit annoying.

**Comment by quyin** [comment] 2017-05-02 20:15
+1. It happens here too.

**Comment by stanislavhannes** [comment] 2017-07-31 22:49
+1

**Comment by ByteThis** [comment] 2017-09-17 06:45
+1. One tab @ the home directory, the focused one working as intended.

**Comment by kirb** [comment] 2017-11-20 10:20
Fixed in ef98224 for the upcoming release.

**Closed as completed by kirb** 2017-11-20 10:20 UTC
Labels: bug

**Comment by ccasares** [comment] 2018-12-31 18:17
still happening with 1.2.1 (9) in Mojave (10.14.2)

**Comment by hitzhangjie** [comment] 2019-06-15 00:41
still happening with 1.2.1 (9) in Mojave (10.14.2)
